export const states: { value: string; label: string }[] = [
  { value: 'ANDHRA_PRADESH', label: 'Andhra Pradesh' },
  { value: 'ARUNACHAL_PRADESH', label: 'Arunachal Pradesh' },
  { value: 'ASSAM', label: 'Assam' },
  { value: 'BIHAR', label: 'Bihar' },
  { value: 'CHHATTISGARH', label: 'Chhattisgarh' },
  { value: 'GOA', label: 'Goa' },
  { value: 'GUJARAT', label: 'Gujarat' },
  { value: 'HARYANA', label: 'Haryana' },
  { value: 'HIMACHAL_PRADESH', label: 'Himachal Pradesh' },
  { value: 'JAMMU_AND_KASHMIR', label: 'Jammu and Kashmir' },
  { value: 'JHARKHAND', label: 'Jharkhand' },
  { value: 'KARNATAKA', label: 'Karnataka' },
  { value: 'KERALA', label: 'Kerala' },
  { value: 'MADHYA_PRADESH', label: 'Madhya Pradesh' },
  { value: 'MAHARASHTRA', label: 'Maharashtra' },
  { value: 'MANIPUR', label: 'Manipur' },
  { value: 'MEGHALAYA', label: 'Meghalaya' },
  { value: 'MIZORAM', label: 'Mizoram' },
  { value: 'NAGALAND', label: 'Nagaland' },
  { value: 'ODISHA', label: 'Odisha' },
  { value: 'PUNJAB', label: 'Punjab' },
  { value: 'RAJASTHAN', label: 'Rajasthan' },
  { value: 'SIKKIM', label: 'Sikkim' },
  { value: 'TAMIL_NADU', label: 'Tamil Nadu' },
  { value: 'TELANGANA', label: 'Telangana' },
  { value: 'TRIPURA', label: 'Tripura' },
  { value: 'UTTAR_PRADESH', label: 'Uttar Pradesh' },
  { value: 'UTTARAKHAND', label: 'Uttarakhand' },
  { value: 'WEST_BENGAL', label: 'West Bengal' },
  { value: 'DELHI', label: 'Delhi' },
  { value: 'CHANDIGARH', label: 'Chandigarh' },
  { value: 'OTHER', label: 'Other' },
];

export const countries: { value: string; label: string }[] = [
  { value: 'INDIA', label: 'India' },
  { value: 'USA', label: 'USA' },
  { value: 'UK', label: 'UK' },
  { value: 'CANADA', label: 'Canada' },
  { value: 'AUSTRALIA', label: 'Australia' },
  { value: 'NEW_ZEALAND', label: 'New Zealand' },
  { value: 'SOUTH_AFRICA', label: 'South Africa' },
  { value: 'UNITED_KINGDOM', label: 'United Kingdom' },
  { value: 'UNITED_STATES', label: 'United States' },
  { value: 'OTHER', label: 'Other' },
];

export const currencies: { value: string; label: string }[] = [
  { value: 'INR', label: 'Indian Rupee' },
  { value: 'USD', label: 'United States Dollar' },
  { value: 'EUR', label: 'Euro' },
  { value: 'GBP', label: 'British Pound' },
  { value: 'CAD', label: 'Canadian Dollar' },
  { value: 'AUD', label: 'Australian Dollar' },
  { value: 'NZD', label: 'New Zealand Dollar' },
  { value: 'ZAR', label: 'South African Rand' },
];

